    
 on:
          workflow_dispatch:
            inputs:
              # Optional inputs for manual runs
              logLevel:
                description: 'Log level'
                required: true
                default: 'info'